FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY data_broker.py .
COPY utils.py .
COPY .env .

CMD ["python", "data_broker.py"]