FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY mqtt_config/certs/ca.crt .
COPY backend/mqtt_broker_processor.py .
COPY backend/utils.py .
COPY backend/.env .

CMD ["python", "mqtt_broker_processor.py"]